# Generated by Django 4.2 on 2023-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_estudios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregable",
            name="fecha_entrega",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
