# Generated by Django 4.2 on 2023-05-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("control_estudios", "0002_alter_entregable_fecha_entrega_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name_plural": "profesores"},
        ),
        migrations.AddField(
            model_name="curso",
            name="creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profesor",
            name="creador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
